apiVersion: taikun.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: providerconfig-workshop
spec:
  credentials:
    source: Secret
    secretRef:
      name: my-creds
      namespace: crossplane-system
      key: credentials
