apiVersion: project.taikun.jet.crossplane.io/v1alpha1
kind: Project
metadata:
  name: "myproject"
spec:
  forProvider:
    name: "test-workshop"
    cloudCredentialIdRef:
            name: "myopencred"
    organizationIdRef:
            name: "myorg"
    lock: false
    monitoring: false
    kubernetesProfileIdRef:
            name: "mykubeprofile"
    accessProfileIdRef:
            name: "myaccprofile"
    alertingProfileIdRef:
            name: "myalertprofile"
    flavors:
      - "m1.medium"
      - "m1.large"
    images:
      - "b2a2939d-3609-4f15-92b7-b5dc3dd5c9d3"
  providerConfigRef:
    name: providerconfig-workshop
---
apiVersion: projectuserattachment.taikun.jet.crossplane.io/v1alpha1
kind: UserAttachment
metadata:
  name: user-attachment-workshop
spec:
  forProvider:
    userIdRef:
            name: "myuser"
    projectIdRef:
            name: "myproject"
  providerConfigRef:
    name: providerconfig-workshop
