apiVersion: user.taikun.jet.crossplane.io/v1alpha1
kind: User
metadata:
    name: myuser
spec:
  forProvider:
    userName: "test-workshop"
    email: "test@test.com"
    role: "User"
    organizationIdRef:
            name: "myorg"
  providerConfigRef:
    name: providerconfig-workshop
---
apiVersion: accessprofile.taikun.jet.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: myaccprofile
spec:
  forProvider:
    name: "test-workshop"
    organizationIdRef:
            name: "myorg" 
    sshUser:
      - name: "test-key"
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGQwGpzLk0IzqKnBpaHqecLA+X4zfHamNe9Rg3CoaXHF :oui_oui:"
  providerConfigRef:
    name: providerconfig-workshop
